name: Contributions Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/metrics/contributions_metrics.svg
          token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
          base: ""
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_skipped: >-
            is-veeam-academy
