name: Isocalendar Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
          filename: .github/metrics/isocalendar_metrics.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
